// Code generated by go-swagger; DO NOT EDIT.

// Package restapi of Product API
//
//	# Documentation for Product API
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
