// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "# Documentation for Product API",
    "title": "of Product API",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/products": {
      "get": {
        "tags": [
          "products"
        ],
        "summary": "Returns the list of products.",
        "operationId": "listProducts",
        "responses": {
          "200": {
            "$ref": "#/responses/productsResponse"
          },
          "500": {
            "$ref": "#/responses/errorResponse"
          }
        }
      },
      "post": {
        "tags": [
          "products"
        ],
        "summary": "Adds a new product.",
        "operationId": "addProduct",
        "responses": {
          "201": {
            "$ref": "#/responses/productResponse"
          },
          "400": {
            "$ref": "#/responses/errorResponse"
          }
        }
      }
    },
    "/products/{id}": {
      "put": {
        "tags": [
          "products"
        ],
        "summary": "Updates an existing product.",
        "operationId": "updateProduct",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "x-go-name": "ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "schema": {}
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/productResponse"
          },
          "400": {
            "$ref": "#/responses/errorResponse"
          },
          "404": {
            "$ref": "#/responses/errorResponse"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "x-go-package": "product-api/data"
    }
  },
  "responses": {
    "errorResponse": {
      "description": ""
    },
    "productResponse": {
      "description": ""
    },
    "productsResponse": {
      "description": "",
      "schema": {
        "type": "array",
        "items": {}
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "# Documentation for Product API",
    "title": "of Product API",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/products": {
      "get": {
        "tags": [
          "products"
        ],
        "summary": "Returns the list of products.",
        "operationId": "listProducts",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "array",
              "items": {}
            }
          },
          "500": {
            "description": ""
          }
        }
      },
      "post": {
        "tags": [
          "products"
        ],
        "summary": "Adds a new product.",
        "operationId": "addProduct",
        "responses": {
          "201": {
            "description": ""
          },
          "400": {
            "description": ""
          }
        }
      }
    },
    "/products/{id}": {
      "put": {
        "tags": [
          "products"
        ],
        "summary": "Updates an existing product.",
        "operationId": "updateProduct",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "x-go-name": "ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "schema": {}
          }
        ],
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": ""
          },
          "404": {
            "description": ""
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "x-go-package": "product-api/data"
    }
  },
  "responses": {
    "errorResponse": {
      "description": ""
    },
    "productResponse": {
      "description": ""
    },
    "productsResponse": {
      "description": "",
      "schema": {
        "type": "array",
        "items": {}
      }
    }
  }
}`))
}
