// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddProductCreatedCode is the HTTP code returned for type AddProductCreated
const AddProductCreatedCode int = 201

/*
AddProductCreated add product created

swagger:response addProductCreated
*/
type AddProductCreated struct {
}

// NewAddProductCreated creates AddProductCreated with default headers values
func NewAddProductCreated() *AddProductCreated {

	return &AddProductCreated{}
}

// WriteResponse to the client
func (o *AddProductCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddProductBadRequestCode is the HTTP code returned for type AddProductBadRequest
const AddProductBadRequestCode int = 400

/*
AddProductBadRequest add product bad request

swagger:response addProductBadRequest
*/
type AddProductBadRequest struct {
}

// NewAddProductBadRequest creates AddProductBadRequest with default headers values
func NewAddProductBadRequest() *AddProductBadRequest {

	return &AddProductBadRequest{}
}

// WriteResponse to the client
func (o *AddProductBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
