// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListProductsOKCode is the HTTP code returned for type ListProductsOK
const ListProductsOKCode int = 200

/*
ListProductsOK list products o k

swagger:response listProductsOK
*/
type ListProductsOK struct {

	/*
	  In: Body
	*/
	Payload []any `json:"body,omitempty"`
}

// NewListProductsOK creates ListProductsOK with default headers values
func NewListProductsOK() *ListProductsOK {

	return &ListProductsOK{}
}

// WithPayload adds the payload to the list products o k response
func (o *ListProductsOK) WithPayload(payload []any) *ListProductsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list products o k response
func (o *ListProductsOK) SetPayload(payload []any) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProductsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]any, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListProductsInternalServerErrorCode is the HTTP code returned for type ListProductsInternalServerError
const ListProductsInternalServerErrorCode int = 500

/*
ListProductsInternalServerError list products internal server error

swagger:response listProductsInternalServerError
*/
type ListProductsInternalServerError struct {
}

// NewListProductsInternalServerError creates ListProductsInternalServerError with default headers values
func NewListProductsInternalServerError() *ListProductsInternalServerError {

	return &ListProductsInternalServerError{}
}

// WriteResponse to the client
func (o *ListProductsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
