// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateProductOKCode is the HTTP code returned for type UpdateProductOK
const UpdateProductOKCode int = 200

/*
UpdateProductOK update product o k

swagger:response updateProductOK
*/
type UpdateProductOK struct {
}

// NewUpdateProductOK creates UpdateProductOK with default headers values
func NewUpdateProductOK() *UpdateProductOK {

	return &UpdateProductOK{}
}

// WriteResponse to the client
func (o *UpdateProductOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateProductBadRequestCode is the HTTP code returned for type UpdateProductBadRequest
const UpdateProductBadRequestCode int = 400

/*
UpdateProductBadRequest update product bad request

swagger:response updateProductBadRequest
*/
type UpdateProductBadRequest struct {
}

// NewUpdateProductBadRequest creates UpdateProductBadRequest with default headers values
func NewUpdateProductBadRequest() *UpdateProductBadRequest {

	return &UpdateProductBadRequest{}
}

// WriteResponse to the client
func (o *UpdateProductBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateProductNotFoundCode is the HTTP code returned for type UpdateProductNotFound
const UpdateProductNotFoundCode int = 404

/*
UpdateProductNotFound update product not found

swagger:response updateProductNotFound
*/
type UpdateProductNotFound struct {
}

// NewUpdateProductNotFound creates UpdateProductNotFound with default headers values
func NewUpdateProductNotFound() *UpdateProductNotFound {

	return &UpdateProductNotFound{}
}

// WriteResponse to the client
func (o *UpdateProductNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
